spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/lemmitools   # Datasource note use jdbc-url for multiple dbs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

secondDB:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url : jdbc:postgresql://localhost/trvanskeddb
    username : postgres
    password : ${PSQL_PWD}



